import streamlit as st
import json
import os
from groq import Groq

# Initialize Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

st.set_page_config(
    page_title="Autonomous Patient Risk Review",
    layout="centered"
)

st.title("🤖 Autonomous Patient Risk Review & Recommendation System")
st.write("Agentic system using outputs from Problem 1 & 2")

# -------- INPUT (TEXT, NOT PARSED) --------
patient_text = st.text_area(
    "Paste Structured Patient Data (from Problem 2)",
    height=260,
    placeholder="""
{
  "patient_name": "Anil Kumar",
  "age": 60,
  "gender": "Male",
  "symptoms": ["Chest pain", "breathlessness"],
  "diagnosis": "Coronary Artery Disease",
  "medications": ["Aspirin", "Clopidogrel"]
}
"""
)

# -------- LOAD GUIDELINES --------
with open("guidelines.txt", "r", encoding="utf-8") as f:
    guidelines = f.read()

# -------- AGENTIC ANALYSIS (LLM HANDLES STRUCTURE) --------
def agentic_analysis(patient_text: str, guidelines: str) -> dict:
    prompt = f"""
You are an autonomous medical agent system.

The following is STRUCTURED patient data generated by a previous system:
{patient_text}

Clinical Guidelines:
{guidelines}

Tasks:
1. Compute patient risk score (0–100)
2. Assign risk level (Low / Medium / High)
3. Identify key risk factors
4. Provide clinical recommendations
5. Explain reasoning

Return ONLY valid JSON with fields:
- patient_name
- risk_score
- risk_level
- key_risk_factors
- recommendations
- explanation
"""

    response = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        temperature=0,
        messages=[{"role": "user", "content": prompt}]
    )

    raw = response.choices[0].message.content.strip()

    if raw.startswith("```"):
        raw = raw.replace("```json", "").replace("```", "").strip()

    return json.loads(raw)

# -------- UI ACTION --------
if st.button("⚡ Analyze Patient Risk"):
    try:
        with st.spinner("Running agentic analysis..."):
            result = agentic_analysis(patient_text, guidelines)

        st.success("Analysis Completed")

        st.subheader("Risk Assessment")
        st.write(f"**Risk Score:** {result['risk_score']}")
        st.write(f"**Risk Level:** {result['risk_level']}")

        st.subheader("Key Risk Factors")
        st.write(result["key_risk_factors"])

        st.subheader(" Recommendations")
        st.write(result["recommendations"])

        st.subheader(" Explanation")
        st.write(result["explanation"])

    except Exception as e:
        st.error("Analysis failed")
        st.text(str(e))

st.markdown("---")
st.caption("Agentic AI System using Free LLaMA-3.1 (Groq)")
